### ISSUE TITLE
cxx packaging job should be less frequent

### ISSUE THREAD

**Issue by tkelman** [staticfloat/julia-buildbot#23]
@staticfloat I'd take a stab at this myself but would probably miss a few places - right now these builds occupy the packaging buildbot for a while, since they do `make -C deps distclean-llvm` every time. Probably makes sense to do these one or a handful of times a day rather than on every successful build. Honestly all the other nightlies could probably be made less frequent too, though the immediate feedback is kinda neat. Depends whether the S3 space is burning a hole in anyone's pocket. I think it's a little more useful to archive the same total space worth of nightlies going further back rather than more frequent.

**Comment by staticfloat** [comment]
The way we're doing it right now is keeping the last month of anything in the `julianightlies` bucket, but I agree that it's a good idea to cut down on the number of jobs.  I'm changing most of the "nightlies" to run every 12 hours instead of every 8, and the `cxx` build will become one of those.  I'm not sure keeping more than a months is worthwhile, what do you think?

**Comment by tkelman** [comment]
It can occasionally help in getting a quick start and end point for bisecting, but you usually have to go to a source build to get all the way down to a single commit anyway. Needing to go to a source build for further-back bisection isn't too bad.
